[build]
  publish = ".next"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "22.14.0"
  NPM_VERSION = "10.9.2"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"